fix: for php5.3, change called function via hook from anonymous function to public function
In php5.3, can't use $this in anonymous function.
Cause an error.
Fatal error: Using $this when not in object context